
service: videoThumbnailGenerator
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  memorySize: 128
  
plugins:
  - serverless-offline

functions:
  ThumbnailGenerator:
    handler: index.handler    
#  Role: >-
#         arn:aws:iam::443202979295:role/service-role/BackupAppLambdaCalled-role-okuntcp4
#       Events:
#         SNS1:
#           Type: SNS
#           Properties:
#             Topic:
#               Ref: SNSTopic1
#   SNSTopic1:
#     Type: "AWS::SNS::Topic"

